'use client';

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import {
  ChartContainer,
} from '@/components/ui/chart';
import { RadialBar, RadialBarChart } from 'recharts';
import { Sparkles, Lightbulb } from 'lucide-react';
import type { GenerateMoleculeRepurposingSuggestionsOutput } from '@/ai/flows/generate-molecule-repurposing-suggestions';

type AiInsightsCardProps = {
  data: GenerateMoleculeRepurposingSuggestionsOutput | null;
  isLoading: boolean;
};

export function AiInsightsCard({ data, isLoading }: AiInsightsCardProps) {
  const chartData = [{ name: 'score', value: data?.repurposingScore ?? 0, fill: "hsl(var(--primary))" }];

  return (
    <Card className="shadow-lg border-2 border-primary/20">
      <CardHeader>
        <div className="flex items-center gap-2">
            <Lightbulb className="h-6 w-6 text-primary" />
            <CardTitle className="text-xl">AI-Driven Insights & Repurposing</CardTitle>
        </div>
        <CardDescription className="text-base">Generated by AI to uncover novel opportunities.</CardDescription>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="md:col-span-2 space-y-3">
              <Skeleton className="h-6 w-1/3" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-5/6" />
            </div>
            <div className="flex items-center justify-center">
              <Skeleton className="h-36 w-36 rounded-full" />
            </div>
          </div>
        ) : data ? (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-center">
            <div className="md:col-span-2">
                <h3 className="font-semibold text-lg mb-2 flex items-center gap-2"><Sparkles className="h-5 w-5 text-accent"/>Insights</h3>
                <p className="text-base text-muted-foreground whitespace-pre-wrap">
                    {data.insights}
                </p>
            </div>
            <div className="flex flex-col items-center justify-center">
                 <ChartContainer config={{}} className="mx-auto aspect-square h-[150px]">
                    <RadialBarChart
                        data={chartData}
                        startAngle={90}
                        endAngle={-270}
                        innerRadius="70%"
                        outerRadius="100%"
                        barSize={12}
                        cy="50%"
                    >
                        <RadialBar
                        dataKey="value"
                        background={{ fill: 'hsl(var(--muted))' }}
                        cornerRadius={10}
                        />
                        <text
                            x="50%"
                            y="50%"
                            textAnchor="middle"
                            dominantBaseline="middle"
                            className="fill-foreground text-3xl font-bold"
                        >
                            {data.repurposingScore}
                        </text>
                        <text
                            x="50%"
                            y="65%"
                            textAnchor="middle"
                            dominantBaseline="middle"
                            className="fill-muted-foreground text-xs"
                        >
                            Score
                        </text>
                    </RadialBarChart>
                </ChartContainer>
                 <p className="text-center font-semibold text-lg mt-2">Repurposing Score</p>
            </div>
          </div>
        ) : (
          <div className="text-center py-10 text-muted-foreground">
            <p>Submit a query to generate AI insights.</p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
